//! Task 16.2 -- maps the external product shape onto Ahlan's native
//! `ProductCreateRequest`.
//!
//! This function is deliberately pure: external struct in, native struct
//! out, or an error. It does NOT call `Catalog::create_product`, does NOT
//! touch `AppState`, and does NOT call any HTTP handler. Per the ADR
//! ("native API plus adapter"), this module's only job is translation --
//! the actual creation still goes through the exact same
//! `ProductCreateRequest::validate()` + `Catalog::create_product` path the
//! native REST/GraphQL create endpoints already use. Wiring this function
//! to an HTTP entry point is a later task, not this one.

use serde::Deserialize;
use thiserror::Error;

use crate::dto::ProductCreateRequest;

/// The external system's own product shape. Field names match the
/// external system's vocabulary on purpose -- this struct exists to
/// *receive* that vocabulary, not to translate it. Deserialize only.
#[derive(Debug, Clone, Deserialize)]
pub struct ExternalProduct {
    pub external_id: String,
    pub name: String,
    pub slug: String,
    pub price: String,
    pub stock: i64,
    pub is_visible: bool,
}

#[derive(Debug, Error, PartialEq, Eq)]
pub enum AdapterError {
    /// Named after the EXTERNAL field ("price"), not the native one
    /// ("price_cents") -- per the ADR's consequence that adapter errors
    /// must read sensibly against what the external caller actually sent.
    #[error("external field 'price' ({0:?}) is not a valid decimal amount")]
    InvalidPrice(String),
}

/// Field mapping, per Task 16.2:
///   name        -> title
///   slug        -> handle
///   price       -> price_cents
///   stock       -> inventory_quantity
///   is_visible  -> published
///
/// `external_id` has no native equivalent and is ignored -- native product
/// IDs are always generated by Ahlan (UUIDv7), never taken from an
/// external system. `description` has no external equivalent and always
/// maps to `None`.
///
/// This does NOT call `ProductCreateRequest::validate()`. Whether the
/// mapped result is actually valid (non-empty title, well-formed handle,
/// non-negative price/quantity) is the native path's job, exercised the
/// same way for every caller -- the adapter's only responsibility is
/// getting the field values into the right shape.
pub fn map_external_to_native(
    external: &ExternalProduct,
) -> Result<ProductCreateRequest, AdapterError> {
    let price_cents = parse_price_to_cents(&external.price)?;

    Ok(ProductCreateRequest {
        title: external.name.clone(),
        handle: external.slug.clone(),
        price_cents,
        inventory_quantity: external.stock,
        published: external.is_visible,
        description: None,
    })
}

/// Deterministic decimal-string -> integer-cents conversion. Works on the
/// string directly (no float parsing) so a price like "25.00" can never
/// silently become 2499 or 2501 cents through binary floating-point
/// rounding -- this is money, so the conversion rule has to be exact, not
/// approximate.
///
/// Accepts: an optional sign is NOT accepted (a negative price is always
/// an error, not a negative quantity of money), a whole-number part, and
/// an optional `.` followed by exactly one or two fractional digits.
fn parse_price_to_cents(price: &str) -> Result<i64, AdapterError> {
    let trimmed = price.trim();
    let invalid = || AdapterError::InvalidPrice(price.to_string());

    let mut parts = trimmed.splitn(2, '.');
    let whole_str = parts.next().unwrap_or("");
    let frac_str = parts.next();

    if whole_str.is_empty() || !whole_str.bytes().all(|b| b.is_ascii_digit()) {
        return Err(invalid());
    }
    let whole: i64 = whole_str.parse().map_err(|_| invalid())?;

    let frac_cents: i64 = match frac_str {
        None => 0,
        Some(f) if f.len() == 1 && f.bytes().all(|b| b.is_ascii_digit()) => {
            let d: i64 = f.parse().map_err(|_| invalid())?;
            d * 10
        }
        Some(f) if f.len() == 2 && f.bytes().all(|b| b.is_ascii_digit()) => {
            f.parse().map_err(|_| invalid())?
        }
        Some(_) => return Err(invalid()),
    };

    Ok(whole * 100 + frac_cents)
}

#[cfg(test)]
mod price_parsing_tests {
    use super::*;

    #[test]
    fn parses_a_two_decimal_price() {
        assert_eq!(parse_price_to_cents("25.00"), Ok(2500));
    }

    #[test]
    fn parses_a_one_decimal_price() {
        assert_eq!(parse_price_to_cents("25.5"), Ok(2550));
    }

    #[test]
    fn parses_a_whole_number_price() {
        assert_eq!(parse_price_to_cents("25"), Ok(2500));
    }

    #[test]
    fn parses_a_free_price() {
        assert_eq!(parse_price_to_cents("0.00"), Ok(0));
    }

    #[test]
    fn rejects_more_than_two_decimal_places() {
        assert!(parse_price_to_cents("25.999").is_err());
    }

    #[test]
    fn rejects_non_numeric_input() {
        assert!(parse_price_to_cents("free").is_err());
        assert!(parse_price_to_cents("").is_err());
        assert!(parse_price_to_cents("25.").is_err());
        assert!(parse_price_to_cents(".50").is_err());
    }

    #[test]
    fn rejects_a_negative_price() {
        assert!(parse_price_to_cents("-25.00").is_err());
    }
}